### ISSUE TITLE
[FEAT] 메인 페이지

### ISSUE THREAD

**Issue by duyeong-ko** [Likelion-at-SMWU-10th/rememB-Client#3]
## 📌  Feature Issue

- 메인 페이지
- 라벨 만들기

## 📝  To-do

- [x] 나의 메인 페이지 작성
- [x] 다른사람의 메인 페이지 작성
- [x] 라벨 만들기
- [x] 공유되는 컴포넌트는 같이 만들기
