### ISSUE TITLE
[FIX] 디자인 반영하기

### ISSUE THREAD

**Issue by nayujin-dev** [Likelion-at-SMWU-10th/rememB-Client#37]
## 📌  Feature Issue

- 갓두영이 깜찍하게 만들어온 디자인 반영하기

## 📝  To-do

- [x] 튜토리얼 페이지
- [x] 로그인 페이지
- [x] 초기설정 페이지
- [x] 메인페이지 (myParty & others)
- [x] 일러스트 선택 페이지
- [x] 편지 작성 페이지
- [x] 편지 작성 완료 페이지
