### ISSUE TITLE
[FEAT] API 사용 작업

### ISSUE THREAD

**Issue by nayujin-dev** [Likelion-at-SMWU-10th/rememB-Client#93]
## 📌  Feature Issue

- 껄껄 겁나는군 api연결한거 가지고 데이터 뿌리기~~

## 📝  To-do

- [x] title에 내용 뿌리기 (이름, 디데이, 날짜)
- [x] 네이버, 카카오 로그인 경우 나눠서 myparty => 카카오 생년월일 형식?
- [x] url들 수정 (id값을 url로 주기) => 유진 대략 구현
- [x] 로딩 화면 => (setting.js) 유진 대략 구현
- [ ] 로그인 실패 화면 
- [x] 편지쓴거 post => 두영 대략 구현
- [x] 파티룸에 get (선물들 & 디데이 됐는지 아닌지)
- [x] 롤링페이퍼에 get 
- [x] 밸런스 선택 post 
- [x] 편지 상세보기에 get 
- [x] 네비바에 내 정보 get
